version: "2"
services:
  helloworld:
    build: .
    volumes:
      - ./src:/src
      - ./testcode:/testcode
  fizz:
    build: .
    volumes:
      - ./src:/src
      - ./testcode:/testcode
    command: [pypy, /src/pybibim.py, /testcode/fizzbuzz_with_number_comment.bibim]
  compile:
    build: .
    command: [pypy, /pypy/rpython/bin/rpython, --output=bbm, /src/pybibim.py]
    volumes:
      - ./src:/src
  compile-jit:
    build: .
    command: [pypy, /pypy/rpython/bin/rpython, --output=bbm, --opt=jit, /src/pybibim.py]
    volumes:
      - ./src:/src
  compiled-helloworld:
    build: .
    command: [/src/bbm, /testcode/helloworld.bibim]
    volumes:
      - ./src:/src
      - ./testcode:/testcode
  compiled-fizz:
    build: .
    command: [/src/bbm, /testcode/fizzbuzz_with_number_comment.bibim]
    volumes:
      - ./src:/src
      - ./testcode:/testcode