version: "2"
services:
  helloworld:
    build: .
    volumes:
      - ./src:/src
      - ./testcode:/testcode
  compile:
    build: .
    command: [pypy, /pypy/rpython/bin/rpython, /src/pybibim.py]
    volumes:
      - ./src:/src
  compile-jit:
    build: .
    command: [pypy, /pypy/rpython/bin/rpython, --opt=jit, /src/pybibim.py]
    volumes:
      - ./src:/src
  compiled-helloworld:
    build: .
    command: [/src/pybibim.py, /testcode/helloworld.bibim]
    volumes:
      - ./src:/src
      - ./testcode:/testcode